gpu:
  cuda_device_order: PCI_BUS_ID
  cuda_visible_devices: '0'
  per_process_gpu_memory_fraction: 0.98

hyperparameters:
  batchsize: 30
  epochs: 10000

model:
  signal_type: 'ABP'  # 'ABP' or 'PPG'
  num_layers: 2
  embed_dim: 64
  num_heads: 1
  dim_fc: 200

mimic3:
  paths:
    train: '../ProcessedData/MIMIC3_ABP/MIMIC_ABP_TrSet.npy'
    valid: '../ProcessedData/MIMIC3_ABP/MIMIC_ABP_ValSet.npy'

output:
  directory: './ModelResults/ABPCleansing/BDC/'
